name: blog_client
publish_to: none

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  spine_client: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0
  test:

flutter:
  uses-material-design: true
