name: blog_client
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  spine_client: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  test:

flutter:
  uses-material-design: true
