language: java

jdk:
  - openjdk8

env:
  global:
    - PATH="$PATH:/usr/lib/dart/bin"

before_install:
  - chmod +x gradlew
  - chmod +x ./config/install-pub.sh
  - ./config/install-pub.sh
  - pub global activate protoc_plugin
  - pub global activate dart_code_gen

script: ./gradlew check --stacktrace
